class Login():
    Input_Email_XPATH = ''
    Input_Password_XPATH = ''
    Button_Login_XPATH = ''
    Button_Cancel_XPATH = ''
    Verify_InvalidLogin_XPATH = ''
    Button_Forgot_XPATH = ''
    Verify_ForgotPage_XPATH = ''
    Button_SignUp_XPATH = ''
    Input_SigUpEmail_XPATH = ''
    Verify_TC_XPATH = ''
    Verify_Register_XPATH = ''