name: Appium Automation on macOS

on:
  push:
    branches:
      - master

jobs:
  test-qa:
    name: Run Appium Tests for QA Build
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Node.js (latest)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      # Install Java 8
      - name: Install Java JDK
        run: |
          brew install --cask temurin  # Install OpenJDK from Temurin
          java -version  # Verify Java installation
          export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
          export PATH=$PATH:$JAVA_HOME/bin
          
      # Install Appium and drivers
      - name: Install Appium and Drivers
        run: |
          npm install -g appium appium-doctor
          appium driver install uiautomator2
          appium driver install xcuitest

      # Set up and start Android emulator
      - name: Create and Start Android Emulator
        run: |
          sdkmanager --install 'system-images;android-30;default;x86_64'
          avdmanager create avd -n Pixel_API_30_AOSP -k 'system-images;android-30;default;x86_64' --force
          nohup emulator -avd Pixel_API_30_AOSP -no-window -no-boot-anim &
          # Pixel 8a API 35

      # Wait for Android emulator to boot
      - name: Wait for Android Emulator to Boot
        run: |
          adb wait-for-device
          adb shell input keyevent 82

      # # Set up Android environment
      # - name: Set up Android environment variables
      #   run: |
      #     export ANDROID_HOME=$HOME/Library/Android/sdk
      #     export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator
      #   env:
      #     ANDROID_HOME: ${{ runner.os }}/Library/Android/sdk
      #     PATH: ${{ runner.os }}/Library/Android/sdk/tools:${{ runner.os }}/Library/Android/sdk/platform-tools:$PATH

      # Install Python dependencies
      - name: Install Python Dependencies
        run: |
          pip install Appium-Python-Client
          pip install -r requirements.txt

      # Print iOS simulator information
      - name: Print Platform Version and Device Name for Simulator
        run: |
          echo "Platform Version: $(xcrun simctl list runtimes | grep -oE 'iOS [0-9]+\.[0-9]+' | tail -1)"
          echo "Device Name: $(xcrun simctl list devices | grep -E 'iPhone' | head -1)"

      # Set up and start Android emulator
      - name: Create and Start Android Emulator
        run: |
          sdkmanager --install 'system-images;android-29;default;x86_64'
          avdmanager create avd -n Pixel_API_29_AOSP -k 'system-images;android-29;default;x86_64' --force
          nohup emulator -avd Pixel_API_29_AOSP -no-window -no-boot-anim &

      # Wait for Android emulator to boot
      - name: Wait for Android Emulator to Boot
        run: |
          adb wait-for-device
          adb shell input keyevent 82

      # Start Appium server
      - name: Start Appium Server
        run: |
          appium -v
          appium --allow-insecure=adb_security --port 4723 --address 0.0.0.0 &

      # Run Python Appium tests
      - name: Run Python Appium Tests
        run: |
          pytest --alluredir=./TestResults

      # Publish Allure report
      - name: Publish Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: ./TestResults
