name: Automation Execution1

on:
  push:
    branches:
      - master  # or your target branch
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run Pytest with Allure
      - name: Run tests with pytest and generate allure results
        run: |
          pytest --alluredir=allure-results

      # Step 5: Upload Allure results as an artifact
      - name: Upload Allure Results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results

      # Step 6: Install Allure and generate Allure report
      - name: Install Allure
        run: |
          sudo apt-add-repository ppa:qameta/allure
          sudo apt-get update
          sudo apt-get install allure

      - name: Generate Allure HTML Report
        run: |
          allure generate allure-results --clean -o allure-report

      # Step 7: Upload Allure HTML report as an artifact
      - name: Upload Allure HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
