name: Automation Execution1

on:
  workflow_dispatch:  # Add this to enable manual triggering
  push:
    branches:
      - master  # or your target branch
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install allure-pytest  # Install allure-pytest
          pip install -r requirements.txt

      # Step 4: Run Pytest with Allure
      - name: Run tests with pytest and generate allure results
        run: |
          pytest --alluredir=allure-results

      # Step 5: Generate Allure Report
      - name: Generate Allure report
        run: |
          allure generate allure-results --clean -o allure-report

      # Step 6: Upload Allure report as an artifact
      - name: Upload Allure report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report

      # Step 7: Deploy to GitHub Pages (optional)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub's built-in token for auth
          publish_dir: ./allure-report
          publish_branch: gh-pages
