name: Appium Python Mobile Automation

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  setup-run-publish:
    runs-on: macos-latest

    env:
      JAVA_HOME: /Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home
      ANDROID_HOME: $HOME/Library/Android/sdk
      PATH: $ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$ANDROID_HOME/cmdline-tools/latest/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Java JDK
      - name: Set up Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install Node.js version 20
      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-python-commons allure-behave

      # Install Homebrew
      - name: Install Homebrew
        run: |
          echo "Installing Homebrew..."
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile
          eval "$(/opt/homebrew/bin/brew shellenv)"
      
      # Install Allure CLI using Homebrew
      - name: Install Allure CLI
        run: |
          brew install allure

      # Install Android SDK command-line tools
      - name: Install Android SDK
        run: |
          echo "Installing Android SDK..."
          mkdir -p $ANDROID_HOME/cmdline-tools
          curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-mac-8092744_latest.zip
          unzip sdk-tools.zip -d $ANDROID_HOME/cmdline-tools
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          
          # Fix PATH issue
          echo "Setting up PATH for sdkmanager"
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH

          # Verify sdkmanager installation
          sdkmanager --version

      # Accept licenses for SDK components
      - name: Accept SDK Licenses
        run: |
          echo "Accepting licenses..."
          yes | sdkmanager --licenses

      # Install Android Emulator components
      - name: Install Android Emulator
        run: |
          sdkmanager "platform-tools" "platforms;android-30" "system-images;android-30;google_apis;x86_64" "emulator"

      # Create and start an Android Emulator
      - name: Create and Start Android Emulator
        run: |
          echo "Creating Android Emulator..."
          echo "no" | avdmanager create avd -n test_emulator -k "system-images;android-30;google_apis;x86_64" --force
          echo "Starting the Android Emulator..."
          emulator -avd test_emulator -no-window -no-audio -no-snapshot &

      # Wait for the emulator to boot
      - name: Wait for Emulator to Boot
        run: |
          echo "Waiting for the emulator to boot..."
          adb wait-for-device
          until adb shell getprop sys.boot_completed | tr -d '\r' | grep -m 1 '1'; do
            sleep 5
          done
          echo "Emulator is ready."

      # List active Android Emulators
      - name: List Active Android Emulators
        run: |
          echo "Active Android Emulators:"
          adb devices
