name: CreateTag

on:
  schedule:
    - cron: "0 1 * * 5" # Runs every Friday at 1AM UTC
  push:
    branches:
      - master

jobs:
  RunTests:
    runs-on: ubuntu-latest

    env:
      majorVersion: '23'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python and install dependencies
        run: |
          SEPARATOR="==================================================="
          YELLOW="\033[0;33m"
          RESET="\033[0m"

          echo -e "${YELLOW}$SEPARATOR\n${YELLOW}Setting Python\n${YELLOW}$SEPARATOR${RESET}"
          sudo apt-get update
          sudo apt-get install google-chrome-stable
          google-chrome --version
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Allure CLI
        run: |
          SEPARATOR="==================================================="
          YELLOW="\033[0;33m"
          RESET="\033[0m"

          echo -e "${YELLOW}$SEPARATOR\n${YELLOW}Install Allure CLI\n${YELLOW}$SEPARATOR${RESET}"
          sudo apt-get install npm
          npm install -g allure-commandline --save-dev
          allure --version

      - name: Run Testcases
        run: |
          SEPARATOR="==================================================="
          YELLOW="\033[0;33m"
          RESET="\033[0m"

          echo -e "${YELLOW}$SEPARATOR\n${YELLOW}Run Pytest\n${YELLOW}$SEPARATOR${RESET}"
          pytest --alluredir=./TestResults
          ls

          echo -e "${YELLOW}$SEPARATOR\n${YELLOW}Listing Results Directory\n${YELLOW}$SEPARATOR${RESET}"
          ls -ltr ./TestResults
        continue-on-error: true

      - name: Generate Test Reports
        run: |
          SEPARATOR="==================================================="
          YELLOW="\033[0;33m"
          RESET="\033[0m"

          echo -e "${YELLOW}$SEPARATOR\n${YELLOW}Generate Reports\n${YELLOW}$SEPARATOR${RESET}"
          allure generate --clean ./TestResults --report-dir ./Report --single-file
          pwd

      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: Reports
          path: ./Report

      - name: Publish Allure Report
        uses: mikepenz/action-allure-report@v2
        with:
          allure_version: "2.27.0"
          results: "./TestResults"
