name: Get Repository Path

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Print the repository path
      - name: Print repository path
        run: echo "Repository path: $GITHUB_WORKSPACE"

      # Step 3: List files in the repository
      - name: List repository files
        run: |
          cd $GITHUB_WORKSPACE
          ls -l
